name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - name: install functions packages
        working-directory: ./functions
        run: npm install
      - name: Build development
        run: CI=false yarn build:dev
      - name: Deploy development
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=dev --debug
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DEV }}
      - name: Build production
        run: CI=false yarn build:prod
      - name: Deploy production
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=prod
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
