name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: CI=false yarn build:dev
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
# jobs:
#   build_and_deploy:
#     name: Build and deploy
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: "16"
#           cache: "yarn"
#       - run: yarn install
#       - run: CI=false yarn build:dev
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#           args: deploy :[environment "dev"]
#         env:
#           GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DEV }}
